### ISSUE TITLE
Error in "gulp build-electron": Can't open output file

### ISSUE THREAD

**Issue by FlipOneDev** [jasimea/ElectronAngular#2]
After doing "gulp build" and "gulp build-electron" on my Windows 10 machine, I got these messages:

::
Processing config: C:\Program Files (x86)\NSIS\nsisconf.nsh
Processing script file: "C:\Projects\Electron\ElectronAngular\dist\installer.nsi" (ACP)
Processed 1 file, writing output (x86-ansi):
Output: "C:\Projects\Electron\ElectronAngular"
Can't open output file
Error - aborting creation process
[05:18:27] Finished 'build-electron' after 1.4 min
::

Tough to figure out for someone new to Electron and NSIS.

**Comment by AnthoniG** [comment]
I am not o fay with Windows 10 as I have Win7, but it sounds like a permissions problem (Administrative rights). The thing that leads me to this conclusion is ACP.

**Comment by routrahul** [comment]
Am trying on a Win10 VM on my mac, facing the same issue. Process gets aborted "Can't open output file".

**Comment by eduardogalbiati** [comment]
Same problem, windows 7, running CMD as administrator

**Comment by eduardogalbiati** [comment]
Solved...

In line 86 in file 'buil.windows.js' there is no name specified for the Installer.exe

`dest: projectDir.path(),`

You just need to specify the EXE name

`dest: projectDir.path('dist/Installer.exe'),`

**Comment by madstt** [comment]
Thanks, guys.

I've added a PR for this: #3.
